question_data = [{"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "The Doppler effect applies to light.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Celebrities", "type": "boolean", "difficulty": "medium",
                  "question": "Michael Jackson had a pet python named &lsquo;Crusher&rsquo;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "The first televised presidential debate was between Jimmy Carter "
                              "and Gerald Ford.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Israel is 7 hours ahead of New York.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                  "question": "The Japanese Shinkansen beat the French TGV&#039;s speed record "
                              "for fastest electric rail train.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
                  "question": "The proof for the Chinese Remainder Theorem used in Number Theory "
                              "was NOT developed by its first publisher, Sun Tzu.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "The first Maxis game to feature the fictional language "
                              "&quot;Simlish&quot; was The Sims (2000).",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "Ashley Frangipane performs under the stage name Halsey.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "&quot;Windows NT&quot; is a monolithic kernel.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Tony Hawk&#039;s Pro Skater was released in 1999.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Vietnam is the only country in the world that starts with V. ",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "The capital of the US State Ohio is the city of Chillicothe.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Antarctica is the largest desert in the world.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "medium",
                  "question": "The Platypus is a mammal.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "medium",
                  "question": "Formula E is an auto racing series that uses hybrid electric race "
                              "cars.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "For his performance at ComplexCon 2016 in Long Beach, California, "
                              "Skrillex revived his &quot;Mothership&quot; set piece for one "
                              "night only.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In Monster Hunter Generations, guild style is a type of hunting "
                              "style.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "Adolf Hitler was accepted into the Vienna Academy of Fine Arts.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Klingons respect their disabled comrades, and those who are old, "
                              "injuried, and helpless.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Hidden in the files for &quot;Mario Kart Arcade GP&quot; is a "
                              "picture of the Beslan school hostage crisis.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Haggis is traditionally ate on Burns Night.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "Sound can travel through a vacuum.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "medium",
                  "question": "In 2008, Usain Bolt set the world record for the 100 meters with "
                              "one shoelace untied.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "Green Day&#039;s album &#039;American Idiot&#039; is considered a "
                              "&quot;punk rock opera.&quot;",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
